[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/docker/docker"
  revision = "3f7898cfcd537fed9f5df64ae0d11e7a2fa83208"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
